data:
  dataset_directory: "./data/"
  train_set_length: 0.9
  validation_set_length: 0.1

train:
  device: "cuda"
  learning_rate: 0.001
  epochs: 10
  batch_size: 16

logging:
    directory: "experiments"
    sub_directory: "Experiment 1"
    model_name: "BaseNet"
  
model: 
  save_directory: "models"
  name: "BaseNet_1"