data:
  dataset_directory: "./data/"
  train_set_length: 0.9
  validation_set_length: 0.1

train:
  model: BaseNet
  device: "cuda"
  learning_rate: 0.001
  epochs: 2
  batch_size: 16
  print_every: 100

  
model: 
  save_directory: "models"
  name: "BaseNet_1"